name: dquery
version: 3.0.0
description: |
  DQuery is a porting of jQuery in Dart.
homepage: https://github.com/rikulo/dquery
documentation: https://pub.dev/documentation/dquery/latest/
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  intl: any
dev_dependencies:
  test: any
