name: dquery
version: 0.5.3
authors:
- Simon Pai <simonpai@rikulo.org>
- ' Tom Yeh <tomyeh@rikulo.org>'
description: |
  DQuery is a porting of jQuery in Dart.
homepage: http://rikulo.org/
dependencies:
  browser: any
  meta: any
  rikulo_commons: '>=0.7.3'
