name: dquery
version: 0.7.0+6
authors:
- Simon Pai <simonpai@rikulo.org>
- Tom Yeh <tomyeh@rikulo.org>
description: |
  DQuery is a porting of jQuery in Dart.
homepage: https://github.com/rikulo/dquery
documentation: http://blog.rikulo.org/posts/2013/May/General/bootjack-and-dquery/ 
environment:
  sdk: ">=1.2.0"
dependencies:
  intl: any
dev_dependencies:
  browser: any
