name: dquery
version: 0.5.1
description: > 
  DQuery is a porting of jQuery in Dart.
authors:
- Simon Pai <simonpai@rikulo.org>
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/
dependencies:
  browser: any
  meta: any
  rikulo_commons: '> 0.7.3'
